/**
 * Recurrence Engine — pure domain logic for generating recurring task instances.
 *
 * Feature: f1-advanced-features
 * Validates: Requirements 4.2, 4.3, 4.4, 4.7, 4.8
 */

export type RecurrenceType = 'NONE' | 'DAILY' | 'WEEKLY' | 'PERIOD';

export interface RecurrenceConfig {
  type: RecurrenceType;
  startDate: string;    // 'YYYY-MM-DD'
  endDate: string;      // 'YYYY-MM-DD'
  weekdays?: number[];  // 0=Sun ... 6=Sat, used only for WEEKLY
}

export interface RecurrenceGenerationResult {
  instances: Array<{ scheduledDate: string; status: 'GARAGE' | 'SKIPPED' }>;
  skippedDates: string[];
  totalGenerated: number;
  error?: string;
}

/** Maximum number of instances allowed per series. */
const MAX_INSTANCES = 365;

/**
 * Parses a 'YYYY-MM-DD' string into a UTC Date object at midnight.
 * Using UTC prevents daylight-saving shifts from changing the day.
 */
function parseDate(yyyymmdd: string): Date {
  const [year, month, day] = yyyymmdd.split('-').map(Number);
  return new Date(Date.UTC(year, month - 1, day));
}

/**
 * Formats a UTC Date back into 'YYYY-MM-DD'.
 */
function formatDate(date: Date): string {
  const y = date.getUTCFullYear();
  const m = String(date.getUTCMonth() + 1).padStart(2, '0');
  const d = String(date.getUTCDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

/**
 * Advances a UTC date by exactly one day.
 */
function addDay(date: Date): Date {
  return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate() + 1));
}

/**
 * Builds the ordered array of candidate dates for the given config.
 * Does NOT apply the 365-instance guard — that is `countInstances`'s job.
 */
function buildDates(config: RecurrenceConfig): string[] {
  const { type, startDate, endDate, weekdays } = config;
  const dates: string[] = [];

  const start = parseDate(startDate);
  const end = parseDate(endDate);

  if (end < start) {
    return dates;
  }

  if (type === 'DAILY' || type === 'PERIOD') {
    // One instance per calendar day in [startDate, endDate], inclusive.
    let cursor = start;
    while (cursor <= end) {
      dates.push(formatDate(cursor));
      cursor = addDay(cursor);
    }
    return dates;
  }

  if (type === 'WEEKLY') {
    // Instances only on days whose weekday (0=Sun…6=Sat) is in weekdays[].
    const allowedDays = new Set<number>(weekdays ?? []);
    if (allowedDays.size === 0) {
      return dates;
    }
    let cursor = start;
    while (cursor <= end) {
      if (allowedDays.has(cursor.getUTCDay())) {
        dates.push(formatDate(cursor));
      }
      cursor = addDay(cursor);
    }
    return dates;
  }

  // NONE → no instances
  return dates;
}

/**
 * Counts how many instances would be generated by this config.
 * Used to enforce the 365-instance limit before actually generating anything.
 *
 * Requirements 4.2, 4.3, 4.4, 4.7
 */
export function countInstances(config: RecurrenceConfig): number {
  return buildDates(config).length;
}

/**
 * Generates recurrence instances for the given config.
 *
 * - Dates in `existingConflicts` receive status 'SKIPPED'.
 * - All other dates receive status 'GARAGE'.
 * - If the total count exceeds 365, returns an error result with zero instances.
 *
 * Requirements 4.2, 4.3, 4.4, 4.7, 4.8
 */
export function generateRecurrenceInstances(
  config: RecurrenceConfig,
  existingConflicts: Set<string>,
): RecurrenceGenerationResult {
  const total = countInstances(config);

  if (total > MAX_INSTANCES) {
    return {
      error: `O período selecionado geraria ${total} instâncias. O limite é ${MAX_INSTANCES}. Reduza o período para continuar.`,
      instances: [],
      skippedDates: [],
      totalGenerated: 0,
    };
  }

  const dates = buildDates(config);
  const instances: Array<{ scheduledDate: string; status: 'GARAGE' | 'SKIPPED' }> = [];
  const skippedDates: string[] = [];

  for (const date of dates) {
    if (existingConflicts.has(date)) {
      instances.push({ scheduledDate: date, status: 'SKIPPED' });
      skippedDates.push(date);
    } else {
      instances.push({ scheduledDate: date, status: 'GARAGE' });
    }
  }

  return {
    instances,
    skippedDates,
    totalGenerated: instances.length,
  };
}
